// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Preference struct {
	ID            int64
	UserID        int64
	AptGroups     []string
	DigestEnabled bool
	DeliveryTime  pgtype.Time
}

type User struct {
	ID         int64
	TelegramID int64
	Username   pgtype.Text
	CreatedAt  pgtype.Timestamptz
}
