// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: preferences.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPreferences = `-- name: CreatePreferences :one
INSERT INTO preferences (user_id, apt_groups, digest_enabled, delivery_time)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, apt_groups, digest_enabled, delivery_time
`

type CreatePreferencesParams struct {
	UserID        int64
	AptGroups     []string
	DigestEnabled bool
	DeliveryTime  pgtype.Time
}

func (q *Queries) CreatePreferences(ctx context.Context, arg CreatePreferencesParams) (Preference, error) {
	row := q.db.QueryRow(ctx, createPreferences,
		arg.UserID,
		arg.AptGroups,
		arg.DigestEnabled,
		arg.DeliveryTime,
	)
	var i Preference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AptGroups,
		&i.DigestEnabled,
		&i.DeliveryTime,
	)
	return i, err
}

const getPreferencesByUserID = `-- name: GetPreferencesByUserID :one
SELECT id, user_id, apt_groups, digest_enabled, delivery_time FROM preferences WHERE user_id = $1
`

func (q *Queries) GetPreferencesByUserID(ctx context.Context, userID int64) (Preference, error) {
	row := q.db.QueryRow(ctx, getPreferencesByUserID, userID)
	var i Preference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AptGroups,
		&i.DigestEnabled,
		&i.DeliveryTime,
	)
	return i, err
}

const listUsersForDelivery = `-- name: ListUsersForDelivery :many
SELECT u.telegram_id, p.apt_groups
FROM users u
JOIN preferences p ON u.id = p.user_id
WHERE p.digest_enabled = true
  AND p.delivery_time IS NOT NULL
  AND p.delivery_time > date_trunc('minute', NOW() AT TIME ZONE 'UTC')::time - INTERVAL '1 minute'
  AND p.delivery_time <= date_trunc('minute', NOW() AT TIME ZONE 'UTC')::time
`

type ListUsersForDeliveryRow struct {
	TelegramID int64
	AptGroups  []string
}

// half-open window: a late tick still lands, but each time stays due once
func (q *Queries) ListUsersForDelivery(ctx context.Context) ([]ListUsersForDeliveryRow, error) {
	rows, err := q.db.Query(ctx, listUsersForDelivery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersForDeliveryRow
	for rows.Next() {
		var i ListUsersForDeliveryRow
		if err := rows.Scan(&i.TelegramID, &i.AptGroups); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAptGroupsOnly = `-- name: UpdateAptGroupsOnly :execresult
UPDATE preferences
SET apt_groups = $2
WHERE user_id = $1
`

type UpdateAptGroupsOnlyParams struct {
	UserID    int64
	AptGroups []string
}

func (q *Queries) UpdateAptGroupsOnly(ctx context.Context, arg UpdateAptGroupsOnlyParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateAptGroupsOnly, arg.UserID, arg.AptGroups)
}

const updateDigestSettings = `-- name: UpdateDigestSettings :execresult
UPDATE preferences
SET digest_enabled = COALESCE($1::boolean, digest_enabled),
    delivery_time = COALESCE($2::time, delivery_time)
WHERE user_id = $3
`

type UpdateDigestSettingsParams struct {
	Enabled      pgtype.Bool
	DeliveryTime pgtype.Time
	UserID       int64
}

// null arguments leave their column untouched
func (q *Queries) UpdateDigestSettings(ctx context.Context, arg UpdateDigestSettingsParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateDigestSettings, arg.Enabled, arg.DeliveryTime, arg.UserID)
}
